config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "blog_posts#index"
  
  resources :blog_posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord

  has_rich_text :content
  
  validates :title, presence: true
  validates :content, presence: true

  scope :sorted, -> { order(published_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :registerable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @blog_posts = user_signed_in? ? BlogPost.sorted : BlogPost.published.sorted
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params) 
    if @blog_post.save
      redirect_to @blog_post
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to @blog_post
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path 
  end
  
  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :content, :published_at)
  end

  def set_blog_post
    @blog_post = user_signed_in? ? BlogPost.find(params[:id]) : @blog_post = BlogPost.published.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post do |form| %>
  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="my-5"
>
    <%= form.label :content %>
    <%= form.rich_text_area :content %>
  </div>
  <div class="my-5"
>
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, include_blank: true %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1> Edit Blog Post </h1>
<%= render partial: 'form', locals: {blog_post: @blog_post }%>
<%= button_to "delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"} %>

app/views/blog_posts/index.html.erb
<h1>My Blog</h1>
<% @blog_posts.each do |blog_post| %>
  <div>
    <h2><%= link_to blog_post.title, blog_post %></h2>
    <p><%= blog_post.content %></p>
    <% if blog_post.draft? %>
      <div class="p-2 rounded bg-gray-100 text-gray-900">Draft</div>
    <% elsif blog_post.scheduled? %>
      <div class="p-2 rounded bg-yellow-500 text-white">Scheduled</div>
    <% elsif blog_post.published? && user_signed_in? %>
      <div class="p-2 rounded bg-green-400 text-white">Published</div>
    <% end %>
  </div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>Create a new post</h1>
<%= render partial: 'form', locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<%= link_to 'Edit this post', edit_blog_post_path(@blog_post) if  user_signed_in? %>
<h1><%= @blog_post.title %></h1>
<p><%= @blog_post.content %></p>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails template</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="prose mx-auto">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div>
      <%= link_to 'All Posts', root_path %>
      <% if user_signed_in? %>
        <%#= link_to 'Profile', edit_user_registration_path %>
        <%= link_to 'Create new post', new_blog_post_path %>
        <%= button_to 'Log Out', destroy_user_session_path, method: :delete %>
        <%# else %>
        <%#= link_to 'Login', new_user_session_path %>
        <%#= link_to 'Sign Up', new_user_registration_path #%>
        <%# Uncomment the above to enable the buttons above. Change the setting in the user.rb file %>
      <% end %>
      <%= yield %>
    </body>
  </html>